add more information for matched cards
FatimahAreola/MSCI-342-Group-Project pull request #25
Opened 2020-11-19 01:42 UTC by abcotter

In this ticket:

- Added info pulled from the API this will allow us to display Artist details and art information
- displayed the art details when a match occurs

Test:
- ran locally to ensure that the info was pulled correctly and displayed as expected
- ran a local production instance to ensure no errors occurred in prod

**NOTE: when we select the art pieces to build out the art object dictionary, we need to ensure they have the information formatted and stored!**

2020-11-22 01:08 UTC, FatimahAreola commented
This code is pending review because I would like to test the requirements for artist details against the code to query the MET API. **No action required from developer.** PR will be approved pending successful merge and test with GenerateNewArt branch.

2020-11-22 01:23 UTC, FatimahAreola commented
@abcotter Some of the fields added return blank or null value for any artist I test with. Specifically the field "art period" does not return a value for any artist and "art culture" often does not return a value. This is understandable, and to be expected for certain fields given the nature of such an open-source program. How does the front-end handle the display of such cases? I think it would be beneficial to return a value like "Unknown" or "Unavailable" for these things. If there are other similar fields in the MET API that do return values more frequently, maybe we should replace with those.

2020-11-22 19:06 UTC, abcotter commented
@FatimahAreola, if the information is missing it just is left blank, I can also remove these fields? let me know what you think

2020-11-22 20:25 UTC, FatimahAreola commented on frontend/frontend/src/components/MatchPopup.vue
> +							{{ flipped[0].artPeriod }} <br />
```suggestion
```
I would remove this value as it comes up blank for all artists

2020-11-22 20:26 UTC, FatimahAreola commented on server/app.py
> +        "artPeriod": artDetails["period"],
```suggestion
```
recommending removal as appears blank for all art

2020-11-22 20:27 UTC, FatimahAreola commented on server/app.py
> +            "artPeriod": artPieces[x].get("period"),
```suggestion
```
recommending removal as appears blank for all artists

2020-11-22 20:29 UTC, FatimahAreola requested changes
I've requested the removal of the art period since I don't believe it makes sense from a UX perspective to have a field that will always appear blank for our specific game. I will leave the option of culture up to you as a design decision and have provided guidelines on how to test how each artist appears to you offline.

Thanks Abi :)

2020-11-22 21:53 UTC, FatimahAreola commented
The code looks good to me but I am getting an error while testing, it appears that one of the art pieces currently as a test on our main branch (ID 435882) has been taken down from the MET API. I don't believe this should be an issue moving forward as we are changing the Object IDs this sprint but wanted to surface this issue. Would you mind testing on your end to make sure this is the only issue? I'm also assigning @m2qaderi to ensure she can test the branch on her end since this is a little strange.

2020-11-23 00:09 UTC, m2qaderi approved these changes
I tested and it works fine for me!

2020-11-23 00:20 UTC, FatimahAreola requested changes
Was able to test, everything looks great! Please merge from main before I can approve and then you should be good to merge.

2020-11-23 00:23 UTC, FatimahAreola approved these changes

2020-11-23 00:23 UTC, merged