Save favourite artists
FatimahAreola/MSCI-342-Group-Project pull request #26
Opened 2020-11-22 00:43 UTC by CarlaLeal

This PR is related to the story "User can view details related to favourited artists"
** Tasks **
Adjust game summary component so users can save artists. 
Query flask API to store saved artists
Display list of artists and article details 

**Testing**
- Do you see a list of artists from the game?
- Can you save an artist from the game?
- Can you unsave an artist from the game?
- When you go to profile, can you see the artists you saved and are the ones you unsaved omitted?

2020-11-22 03:01 UTC, abcotter requested changes
Looking good Carla, I did notice a rather long delay when routing to the profile and when the users artists load... I think either you should add a loading spinner or pulle the users favourite artists earlier and store them.

currently until the artists are loaded from the API it is displaying the message "No artists favourited yet" which isn't technically true, they are just being loaded in.

2020-11-22 03:01 UTC, abcotter commented on frontend/frontend/src/components/Home copy.vue
> +<template>
What is this copy used for? if it isn't needed for functionality please remove :)

2020-11-22 03:01 UTC, abcotter commented on frontend/frontend/src/components/SavedArtist.vue
> +		</div>
```suggestion
<div class="artist-bin">
		<div class="left">
			<p>{{ artistName }}</p>
		</div>
		<div class="right">
			<button
				class="saveButton"
				v-on:click="
					savedArtist
						? updateArtistRelationship('remove')
						: updateArtistRelationship('save')
				"
			>
				{{ savedArtist ? "UNFAVOURITE" : "FAVOUTIRE" }}
			</button>
		</div>
</div>
```

2020-11-22 03:01 UTC, abcotter commented on frontend/frontend/src/components/SavedArtist.vue
> +		</div>
I'm making some changes here, to allow for better styling in the css

2020-11-22 03:01 UTC, abcotter commented on frontend/frontend/src/components/SavedArtist.vue
> +.left {
```suggestion
.artists {
	display: flex;
	margin: auto;
	justify-content: space-around;
}
.artist-bin {
	display: flex;
	justify-content: space-between;
	width: 300px;
}
.left {
```

2020-11-22 03:01 UTC, abcotter commented on frontend/frontend/src/components/SavedArtist.vue
> +}
```suggestion
}
.right {
	display: inline-block;
	padding-left: 10px;
	padding-top: 12px;
}
```

2020-11-22 03:01 UTC, abcotter commented on frontend/frontend/src/components/SavedArtist.vue
> +	width: 55px;
```suggestion
	margin-top: 2px;
	width: 95px;
```

2020-11-22 03:01 UTC, abcotter commented on server/app.py
> +        query = "SELECT * FROM  UserArtist WHERE userID=%s AND artist=%s"
some of your queries have UserID, but our DB uses UserId... I never had any issues... but maybe for consistency make sure the queries match

2020-11-22 03:01 UTC, abcotter commented on frontend/frontend/src/components/Profile.vue
> +		<h1>Profile</h1>
```suggestion
		<button v-on:click="routeToHome" class="back-button">BACK</button>
		<h1>Profile</h1>
```

Let's add a back button! so the user can always route home

2020-11-22 03:01 UTC, abcotter commented on frontend/frontend/src/components/Profile.vue
> +		});
```suggestion
		});
	methods: {
		routeToHome: function () {
			this.$router.push("/home");
		},
	},
```

2020-11-22 03:01 UTC, abcotter commented on frontend/frontend/src/components/Profile.vue
> +.card {
```suggestion
.back-button {
	position: absolute;
	left: 10px;
	top: 10px;
	/* button */
	margin-top: 2px;
	width: 95px;
	height: 23px;
	border: 2px solid #ffe381;
	background-color: #ffe381;
	/* text */
	font-size: 15px;
	font-weight: bold;
	color: #cf4985;
}
.card {
```

2020-11-22 04:07 UTC, CarlaLeal commented on frontend/frontend/src/components/Home copy.vue
> +<template>
No clue! Will remove :)

2020-11-22 04:11 UTC, CarlaLeal commented
> Looking good Carla, I did notice a rather long delay when routing to the profile and when the users artists load... I think either you should add a loading spinner or pulle the users favourite artists earlier and store them.
> 
> currently until the artists are loaded from the API it is displaying the message "No artists favourited yet" which isn't technically true, they are just being loaded in.

That's a really good point! Let me investigate the loading spinner idea. I don't think the saved artists should be in a global store if they're only going to be used by one component realistically.

2020-11-22 19:13 UTC, abcotter reviewed
@CarlaLeal Looks great! There is only one issue. The "favourited" artists don't seem to be updated and accurate on the game summary page. 

I favourited an artist--> navigated home --> looked at my profile --> went home --> started another game --> then on the game summary page the artist i had previously se to favourited wasn't set correctly

2020-11-22 19:22 UTC, abcotter requested changes

2020-11-22 19:22 UTC, abcotter commented on frontend/frontend/src/components/SavedArtist.vue
> +			savedArtist: false,
I think you should keep a local array in the vuex store called artists or something and when the person logs in we can grab the names of artists they have favourited, then update it locally when we update the database. this way we can set the savedArtist variable based on if the vuex store variable .includes() the artistName

2020-11-22 23:40 UTC, abcotter approved these changes
Looks good

2020-11-23 00:08 UTC, merged

2020-11-23 00:40 UTC, FatimahAreola commented
I think we approved and merged before I completed my review. Understandable since I was having issues with my system. I went back and tested anyway, while a little slow, things are working on my end.