Met API
FatimahAreola/MSCI-342-Group-Project pull request #7
Opened 2020-10-24 19:32 UTC by FatimahAreola

In this PR:
- Return details from the MET API for a set of pre-determined pieces of art 
- Created Folder/Document for us to keep track of testing guidelines

Things to note: 
- I've added json to the requirements.txt document, it is important for anyone trying to run the code to be aware of this

2020-10-24 19:54 UTC, abcotter requested changes
Please look into what is causing the API call to take so long

2020-10-24 19:54 UTC, abcotter commented on app/app.py
> +        'cardName': "Card" +str(idx+1),
for usability to the frontend can this be just cardId
```suggestion
        'cardId': idx+1,
```

2020-10-24 19:54 UTC, abcotter commented on app/app.py
> +@app.route('/api/MetAPI')
The execution time for this API call averaged around 4.35 seconds for me ... what what the performance for you? This is really slow, I'm wondering if the call to the MET API is slow? I would run some performance measures (time breakpoints) to try and isolate whats slowing you down and can it be adjusted to be better.

2020-10-24 19:58 UTC, abcotter commented
@FatimahAreola I think we should explore running the API calls to the MET asyncronously or all at once? running them independently is probably taking longer than needed.

2020-10-24 20:05 UTC, FatimahAreola commented
@abcotter Your suggestion makes sense, I also noticed a lag in the API calls. I do think it is worth noting that the reason I chose not to run the API calls all at once was to make sure the code was still usable when we move forward into future sprints. Down the pipeline we are looking at variable numbers of cards and pieces of art returned - as well as writing methods to determine which pieces of art to use, so making the API call a bit more dynamic was important to me. Do you think there is an effective way to both make the call more dynamic _and_ run all calls at the same time?

2020-10-24 20:13 UTC, abcotter commented
@FatimahAreola  I agree keeping our code dynamic is important for when we introduce varying sized game boards. What if you have a helper function that takes does the call to the MET API? also we could have the API take in a parameter that repersents the game size (i.e we could pass in the number of unique cared we need boardsize/2) and then your api can pull that number of objects

I though the met api could take an array of objectIds? can't we pass them all in? you could also explore calling the api asynchronously so that they are almost lazy loading while you format the result

2020-10-24 20:20 UTC, FatimahAreola commented
> I though the met api could take an array of objectIds? can't we pass them all in? you could also explore calling the api asynchronously so that they are almost lazy loading while you format the result

No, the MET API can't **take** an array of objectIDs, I checked. You are thinking of a different functionality. 

>hat if you have a helper function that takes does the call to the MET API? also we could have the API take in a parameter that repersents the game size (i.e we could pass in the number of unique cared we need boardsize/2) and then your api can pull that number of objects
I spent some time playing with helper functions while writing this code and found complications with passing JSON objects/dictionaries back and forth. I don't think the things you are mentioning are in scope for this sprint - happy to bring this up at our retro and factor them into future sprints. In the meantime I will continue experimenting with how this can be accomplished.

Thanks for your feedback!

2020-10-24 21:15 UTC, CarlaLeal reviewed
This looks good! I looked at the MET API and played around with it. I don't see a way to send multiple ids at once. Another very valid way around this is to use thread pooling for this issue

2020-10-24 21:30 UTC, m2qaderi commented
I think this looks great Fatimah. I agree with Abi's comment about the lag and Carla's suggestion sounds good but I think we should table this for now and all discuss possible solutions at our next meeting

2020-10-24 21:30 UTC, m2qaderi approved these changes

2020-10-24 21:36 UTC, FatimahAreola commented
> thread pooling
Thread pooling sounds like a great suggestion! I am not familiar with it in practice so I'm happy to start researching it as a solution. The game appears playable on my end but I have requested a re-review from Abi to verify on her end.

2020-10-25 02:35 UTC, abcotter commented
@FatimahAreola lets make sure we add a ticket for next sprint to research and implement the thread pooling Carla mentioned.

2020-10-25 02:36 UTC, abcotter approved these changes

2020-10-25 02:37 UTC, merged